accounts/urls.py
from django.contrib.auth import login
from django.urls import path
from .views import LoginView,LogOutView,SingupView
app_name='account'
urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogOutView.as_view(),name='logout'),
    path("register/", SingupView.as_view(), name="register"),
    
]

lesson1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store')),
    path('accunts/',include('accounts.urls',namespace='account'))

]


if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import HomePageView,PrductDetailView,CategoryListView
app_name='store'
urlpatterns = [
    path('',HomePageView.as_view(),name='home'),
    path("productdetails<slug:prod_slug>/", PrductDetailView.as_view(), name="product_detail"),
    path("categoriesdetail/<slug:cat_slug>/", CategoryListView.as_view(), name="category_list"),
    
]

templates/components/footer.html
<footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>test by jatin singh © jatinsingh, but please download and customize it for yourself!</p>
        <p>New to shop? <a href="store:home">Visit the homepage</a>  tech  support number 9880388741</a>.</p>
      </div>
</footer>

templates/components/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'store:home' %}">All</a></li>
             {% for cat in categories %}
             
              <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.genres}}</a></li>
           
             
             {% endfor %}            
          </ul>
       
          
          
     
        </li>
        
      </ul>

      {% if user.is_authenticated %}
           <a href="{% url 'account:logout' %}" class="btn btn-danger">Log Out</a>
           {% else %}
                 <a href="{% url 'account:login' %}" class="btn btn-success">Log In</a> &nbsp;
      <a href="{% url 'account:register' %}" class="btn btn-primary">Register Here</a> &nbsp;

      {% endif %}
      &nbsp;
      <form class="d-flex" method='GET' action="{% url 'store:home' %}">
      
      
        <input class="form-control me-2" type="search" placeholder="Search" type='text' name='search-area' placeholder="Search your task" value="{{search_input}}">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>